# Generated by Django 4.2.5 on 2023-10-24 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_appointment_time_alter_appointment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('person_of_intrest', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('time', models.TimeField(null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department1')),
            ],
        ),
    ]
